"""update_table

Revision ID: 7f3edc86db3a
Revises: 
Create Date: 2025-07-29 11:56:25.332548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3edc86db3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_bonuses', sa.Integer(), nullable=True))
        batch_op.drop_column('aditional_bonuses')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aditional_bonuses', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('additional_bonuses')

    # ### end Alembic commands ###
