"""add_year_and_month_

Revision ID: a72684bcae4c
Revises: 7f3edc86db3a
Create Date: 2025-07-29 17:30:08.616773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72684bcae4c'
down_revision = '7f3edc86db3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_data', schema=None) as batch_op:
        batch_op.drop_column('current_year')
        batch_op.drop_column('current_month')

    # ### end Alembic commands ###
